services:
  pdf_backend:
    build:
      context: ./pdf-summarizer-backend
      dockerfile: Dockerfile
    container_name: pdf_backend
    ports:
      - "8888:8888"
    environment:
      - OLLAMA_API_URL=http://ollama_service:11434/api/chat
      - QDRANT_HOST=qdrant_service
      - QDRANT_PORT=6333
    volumes:
      - ./pdf-summarizer-backend/app:/workspace/app
      - ./db_data:/workspace/db_data
      - ./uploaded_pdfs:/workspace/uploaded_pdfs
    depends_on:
      ollama_service:
        condition: service_started
      qdrant_service:
        condition: service_started
      ollama_model_puller:
        condition: service_completed_successfully
    restart: always

  ollama_service:
    image: ollama/ollama:latest
    container_name: ollama_node
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_storage:/root/.ollama
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama_model_puller:
      image: alpine:latest
      container_name: ollama_init
      depends_on:
        - ollama_service
      entrypoint: >
        sh -c "apk add --no-cache curl &&
               echo 'Waiting for Ollama to boot...' &&
               while ! curl -s http://ollama_service:11434/api/tags > /dev/null; do sleep 2; done &&
               echo 'Pulling Llama 3.2 model weights (this will take 10-15 minutes)...' &&
              curl -f -s -X POST http://ollama_service:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"llama3.2:3b\", \"stream\": false}' &&
              echo 'Pulling Nomic Embed Text model weights...' &&
              curl -f -s -X POST http://ollama_service:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"nomic-embed-text\", \"stream\": false}' &&
              echo 'All models fully cached!'"
  qdrant_service:
    image: qdrant/qdrant:latest
    container_name: qdrant_node
    ports:
      - "6333:6333"
      - "6343:6343"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always